//! The app icon: a `>_` terminal mark generated by `assets/make_icon.py` and
//! checked in as `assets/icon.png` (embedded) + `assets/icon.icns` (for a
//! future .app bundle). `AppAssets` serves it through gpui's asset source so
//! `img(APP_ICON_PATH)` resolves in the About dialog and Profile settings,
//! and `install_dock_icon` applies it to the macOS dock at launch — the
//! runtime equivalent of a bundle icon while the app ships unbundled.

use std::borrow::Cow;

use gpui_kit::*;

/// Asset path the embedded icon answers to — `img(APP_ICON_PATH)` loads it.
pub(crate) const APP_ICON_PATH: &str = "icons/app.png";

/// The 512×512 PNG, embedded so the dock icon and About surfaces work with
/// no filesystem dependency.
const APP_ICON_PNG: &[u8] = include_bytes!("../assets/icon.png");

/// The app's asset source: gpui-kit's full icon catalog plus the app icon.
/// `AllAssets::load` errors on unknown paths, so the icon must be matched
/// before delegating.
pub(crate) struct AppAssets {
    icons: assets::AllAssets,
}

impl AppAssets {
    pub(crate) fn new() -> Self {
        Self { icons: assets::AllAssets::new("") }
    }
}

impl AssetSource for AppAssets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        if path == APP_ICON_PATH {
            return Ok(Some(Cow::Borrowed(APP_ICON_PNG)));
        }
        self.icons.load(path)
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        let mut paths = self.icons.list(path)?;
        if APP_ICON_PATH.starts_with(path) {
            paths.push(APP_ICON_PATH.into());
        }
        Ok(paths)
    }
}

/// The app icon as an element, sized for its surface (About dialog, Profile
/// settings). The id lets headless tests find it.
pub(crate) fn app_icon(id: &'static str, size: f32) -> impl IntoElement {
    img(APP_ICON_PATH).id(id).test_support().size(px(size)).flex_shrink_0()
}

/// Apply the embedded icon to the dock. Skipped when the process already has
/// an icon — a bundled .app's CFBundleIconFile wins over the runtime image.
#[cfg(target_os = "macos")]
pub(crate) fn install_dock_icon() {
    use objc2::MainThreadMarker;
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;

    let Some(mtm) = MainThreadMarker::new() else { return };
    let app = NSApplication::sharedApplication(mtm);
    if app.applicationIconImage().is_some() {
        return;
    }
    let data = NSData::with_bytes(APP_ICON_PNG);
    if let Some(image) = NSImage::initWithData(mtm.alloc(), &data) {
        // SAFETY: main thread (mtm proves it), image is a live NSImage.
        unsafe { app.setApplicationIconImage(Some(&image)) };
    }
}

/// Non-macOS platforms take their taskbar icon from the bundle/window, which
/// gpui doesn't expose — nothing to install at runtime.
#[cfg(not(target_os = "macos"))]
pub(crate) fn install_dock_icon() {}
